import { StyleSheet } from "react-native";

import { COLORS, successWithAlpha } from "@/constants/colors";

export const fastingScheduleModalStyles = StyleSheet.create({
  backdrop: {
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  badgePro: {
    backgroundColor: successWithAlpha(0.15),
    borderColor: successWithAlpha(0.4),
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  badgeProText: {
    color: COLORS.success,
    fontFamily: 'HankenGrotesk_800ExtraBold',
    fontSize: 10,
  },
  closeButton: {
    alignItems: 'center',
    backgroundColor: '#3A3428',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  customDaysBox: {
    backgroundColor: '#211E18',
    borderColor: '#3A3428',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 14,
    padding: 14,
  },
  dayButton: {
    alignItems: 'center',
    backgroundColor: '#2B2620',
    borderColor: '#443D2E',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
  },
  dayButtonActive: {
    backgroundColor: COLORS.success,
    borderColor: COLORS.success,
  },
  dayText: {
    color: '#A79D88',
    fontFamily: 'HankenGrotesk_700Bold',
    fontSize: 11,
  },
  dayTextActive: {
    color: '#3A2200',
  },
  durationBox: {
    flex: 1.4,
  },
  durationScroll: {
    flexDirection: 'row',
    marginTop: 6,
  },
  footer: {
    borderTopColor: '#3A3428',
    borderTopWidth: 1,
    paddingHorizontal: 20,
    paddingTop: 14,
  },
  hPill: {
    alignItems: 'center',
    backgroundColor: '#211E18',
    borderColor: '#3A3428',
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: 'center',
    marginRight: 6,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  hPillActive: {
    backgroundColor: COLORS.success,
    borderColor: COLORS.success,
  },
  hPillText: {
    color: '#F1E9D6',
    fontFamily: 'HankenGrotesk_700Bold',
    fontSize: 13,
  },
  hPillTextActive: {
    color: '#3A2200',
  },
  header: {
    alignItems: 'center',
    borderBottomColor: '#3A3428',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 14,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  headerSubtitle: {
    color: '#A79D88',
    fontFamily: 'HankenGrotesk_400Regular',
    fontSize: 12,
    marginTop: 2,
  },
  headerTitle: {
    color: '#F1E9D6',
    fontFamily: 'HankenGrotesk_800ExtraBold',
    fontSize: 18,
  },
  keyboardContainer: {
    flex: 1,
  },
  presetCard: {
    backgroundColor: '#211E18',
    borderColor: '#3A3428',
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 8,
    padding: 14,
  },
  presetCardActive: {
    backgroundColor: successWithAlpha(0.08),
    borderColor: COLORS.success,
  },
  presetDesc: {
    color: '#A79D88',
    fontFamily: 'HankenGrotesk_400Regular',
    fontSize: 12,
    lineHeight: 16,
    marginTop: 4,
  },
  presetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  presetLabel: {
    color: '#F1E9D6',
    fontFamily: 'HankenGrotesk_700Bold',
    fontSize: 14,
  },
  presetLabelActive: {
    color: COLORS.success,
  },
  presetsGrid: {
    marginTop: 8,
  },
  reminderPill: {
    alignItems: 'center',
    backgroundColor: '#211E18',
    borderColor: '#3A3428',
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 6,
  },
  reminderPillActive: {
    backgroundColor: successWithAlpha(0.15),
    borderColor: COLORS.success,
  },
  reminderRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
  },
  reminderText: {
    color: '#A79D88',
    fontFamily: 'HankenGrotesk_600SemiBold',
    fontSize: 11,
  },
  reminderTextActive: {
    color: COLORS.success,
  },
  safeArea: {
    maxHeight: '90%',
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: COLORS.success,
    borderRadius: 16,
    justifyContent: 'center',
    minHeight: 50,
  },
  saveButtonText: {
    color: '#3A2200',
    fontFamily: 'HankenGrotesk_800ExtraBold',
    fontSize: 15,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  sectionHeading: {
    color: '#F1E9D6',
    fontFamily: 'HankenGrotesk_700Bold',
    fontSize: 13,
    marginTop: 18,
    textTransform: 'uppercase',
  },
  settingsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
  },
  sheetContainer: {
    backgroundColor: '#0F0F12',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '100%',
  },
  subHeading: {
    color: '#A79D88',
    fontFamily: 'HankenGrotesk_600SemiBold',
    fontSize: 12,
    marginBottom: 4,
  },
  timeBox: {
    flex: 0.9,
  },
  timeInput: {
    backgroundColor: '#211E18',
    borderColor: '#3A3428',
    borderRadius: 12,
    borderWidth: 1,
    color: '#F1E9D6',
    fontFamily: 'HankenGrotesk_700Bold',
    fontSize: 16,
    marginTop: 6,
    minHeight: 46,
    textAlign: 'center',
  },
  toggleDesc: {
    color: '#A79D88',
    fontFamily: 'HankenGrotesk_400Regular',
    fontSize: 12,
    lineHeight: 16,
    marginTop: 2,
  },
  toggleLabel: {
    color: '#F1E9D6',
    fontFamily: 'HankenGrotesk_700Bold',
    fontSize: 14,
  },
  toggleRow: {
    alignItems: 'center',
    backgroundColor: '#211E18',
    borderColor: '#3A3428',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
  },
  weekdaysRow: {
    flexDirection: 'row',
    gap: 4,
    marginTop: 6,
  },
});
